name: Zola Build and OG Image Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Bun cache
        uses: actions/cache@v3
        id: bun-cache
        with:
          path: ~/.bun
          key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore node_modules cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: tools/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('tools/bun.lockb') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies (tools)
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        run: bun install --cwd tools

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - name: Build Zola site
        run: zola build

      - name: Generate OG Images
        uses: mujo-code/puppeteer-headful@16.6.0
        env:
          CI: "true"
        with:
          args: bun run tools/genOG.ts

      - name: Check for changes
        id: git-check
        run: echo "::set-output name=modified::$([ -z "$(git status --porcelain)" ] && echo "false" || echo "true")"

      - name: Commit changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add public/og/*
          git commit -m "chore: generated og images"
          git push origin HEAD:main

